# Generated by Django 4.0.1 on 2022-02-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('pickup', 'Pickup'), ('sedan', 'Sedan'), ('universal', 'Universal')], max_length=50)),
                ('drop', models.CharField(max_length=50)),
                ('when', models.CharField(max_length=200)),
            ],
        ),
    ]
